import type { Metadata } from "next";

import "./globals.css";

import { pretendardStd } from "@/components/fonts";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={clsx("font-pretendardStd", pretendardStd.variable)}>
        {children}
      </body>
    </html>
  );
}
