import type { Metadata } from "next";

import "./globals.css";

import { pretendardStd } from "@/components/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendardStd.className}>{children}</body>
    </html>
  );
}
